package common;

public enum PageType {
	HOME_MANAGEMRNT_PAGE, USER_MANAGEMRNT_PAGE, USER_FORM_MANAGEMRNT_PAGE, REPORT_MANAGEMRNT_PAGE,
	VIDEO_MANAGEMRNT_PAGE, VIDEO_FORM_MANAGEMRNT_PAGE, ACCOUNT_LOGIN_PAGE, ACCOUNT_CHANGE_INFORMATION_PAGE,
	ACCOUNT_CHANGE_PASSWORD_PAGE, ACCOUNT_FORGOT_PASSWORD_PAGE,

	SITE_HOME_PAGE, SITE_LOGIN_PAGE, SITE_REGISTRATION_PAGE, SITE_CHANGE_PASSWORD_PAGE, SITE_CHANGE_INFORMATION_PAGE,
	SITE_FORGOT_PASSWORD_PAGE, SITE_DETAIL_PAGE, SITE_ABOUT_PAGE, SITE_CONTACT_PAGE, SITE_FAVORITE_PAGE
}
